### ISSUE TITLE
In vro the _make check_ fail with LookupError: _Invalid transducer header_, individual rerun passes (Bugzilla Bug 1986)

### ISSUE THREAD

**Issue by albbas** [divvungiellatekno/divvun.no#292]
This issue was created automatically with bugzilla2github
# Bugzilla Bug 1986
Date: 2015-02-18T05:08:46+01:00
From: @rueter (Originally created by @rueter)
To:   @snomos
CC:   @leneantonsen, @lynnda-hill, @mka055, @snomos, @duomdaamaendra, @Trondtr

Last updated: 2015-02-23T17:06:07+01:00

**Comment by albbas** [comment]
## Comment 10194
Date: 2015-02-18 05:08:46 +0100
From: @rueter

after _make check_ there are failures

+++++
YAML test 119: analyser-gt-norm.hfst + gt-norm-yamls/V-vaesuemae74_gt-norm.yaml - Traceback (most recent call last):
  File "/home/rueter/main/gtcore/scripts/morph-test.py", line 682, in <module>
    main()
  File "/home/rueter/main/gtcore/scripts/morph-test.py", line 674, in main
    ui.start()
  File "/home/rueter/main/gtcore/scripts/morph-test.py", line 667, in start
    ret = self.test.run()
  File "/home/rueter/main/gtcore/scripts/morph-test.py", line 256, in run
    self.run_tests(self.args.test)
  File "/home/rueter/main/gtcore/scripts/morph-test.py", line 334, in run_tests
    self.run_test(t, True)
  File "/home/rueter/main/gtcore/scripts/morph-test.py", line 416, in run_test
    raise LookupError('`%s` had an error:\n%s' % (self.program, self.results['err']))
__main__.LookupError: `['/usr/local/bin/hfst-optimized-lookup']` had an error:
Invalid transducer header.
The transducer must be in optimized lookup format.
(Error code: 1)
FAIL

To rerun with more details, please triple-click, copy and paste the following:

pushd /home/rueter/main/langs/vro/test/src; /usr/bin/python3 /home/rueter/main/gtcore/scripts/morph-test.py -c -i -v -S hfst --app /usr/local/bin/hfst-optimized-lookup --morph ././../../src/analyser-gt-norm.hfst --gen ././../../src/generator-gt-norm.hfst  ./gt-norm-yamls/V-vaesuemae74_gt-norm.yaml; popd


+++++

BUT the individual rerun ALL PASSES

**Comment by albbas** [comment]
## Comment 10195
Date: 2015-02-18 09:29:20 +0100
From: @snomos

Do:

make clean
make
make check

If that doesn't help. try also:

./autogen.sh
./configure --with-hfst --without-xfst

That should solve it. The cause: the fst is in the wrong format after I started using hfst-optimised-lookup for running most of the test (to make the testing go faster).

**Comment by albbas** [comment]
## Comment 10229
Date: 2015-02-23 17:06:07 +0100
From: @snomos

Fixed according to the OP.
