### ISSUE TITLE
Ant xdb:store fails [java.lang.NoClassDefFoundError: org/apache/logging/log4j/message/Message] (Bugzilla Bug 2094)

### ISSUE THREAD

**Issue by albbas** [divvungiellatekno/divvun.no#310]
This issue was created automatically with bugzilla2github
# Bugzilla Bug 2094
Date: 2015-10-14T16:21:42+02:00
From: @tomipieski (Originally created by @tomipieski)
To:   @albbas
CC:   @snomos

Last updated: 2015-11-18T23:27:27+01:00

**Comment by albbas** [comment]
## Comment 10795
Date: 2015-10-14 16:21:42 +0200
From: @tomipieski

I couldn't find a reason why I get this error message when running ant xdb:store in gtweb and gtlab. They both have updated fedora this week.


java.lang.NoClassDefFoundError: org/apache/logging/log4j/message/Message
	at org.exist.xmldb.DatabaseImpl.<clinit>(DatabaseImpl.java:69)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.exist.ant.AbstractXMLDBTask.registerDatabase(AbstractXMLDBTask.java:161)
	at org.exist.ant.XMLDBStoreTask.execute(XMLDBStoreTask.java:85)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
	at org.apache.tools.ant.Main.runBuild(Main.java:851)
	at org.apache.tools.ant.Main.startAnt(Main.java:235)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.message.Message
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 22 more

**Comment by albbas** [comment]
## Comment 10796
Date: 2015-10-14 17:05:06 +0200
From: @albbas

We probably need to install packages that covers this functionality again. 
I'll have a look at it.
